"""create visits table

Revision ID: 8baab3e73d08
Revises: af834253ebc2
Create Date: 2026-08-06 00:44:06.215960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8baab3e73d08'
down_revision: Union[str, Sequence[str], None] = 'af834253ebc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('visit_plan_id', sa.Integer(), nullable=False),
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('visit_status', sa.String(length=30), nullable=False),
    sa.Column('visit_result', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order_exists', sa.Boolean(), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('collection_exists', sa.Boolean(), nullable=False),
    sa.Column('collection_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('collection_notes', sa.Text(), nullable=True),
    sa.Column('need_follow_up', sa.Boolean(), nullable=False),
    sa.Column('next_visit_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.ForeignKeyConstraint(['visit_plan_id'], ['visit_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_code'), 'visits', ['code'], unique=True)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_code'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
