"""create visit plans

Revision ID: af834253ebc2
Revises: 4236d8c327b4
Create Date: 2026-08-05 01:30:02.235947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af834253ebc2'
down_revision: Union[str, Sequence[str], None] = '4236d8c327b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('planned_time', sa.Time(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_plans_code'), 'visit_plans', ['code'], unique=True)
    op.create_index(op.f('ix_visit_plans_id'), 'visit_plans', ['id'], unique=False)
    op.alter_column('representatives', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('representatives', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('representatives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('representatives_code_key'), 'representatives', type_='unique')
    op.create_index(op.f('ix_representatives_code'), 'representatives', ['code'], unique=True)
    op.create_index(op.f('ix_representatives_id'), 'representatives', ['id'], unique=False)
    op.create_index(op.f('ix_representatives_name'), 'representatives', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_representatives_name'), table_name='representatives')
    op.drop_index(op.f('ix_representatives_id'), table_name='representatives')
    op.drop_index(op.f('ix_representatives_code'), table_name='representatives')
    op.create_unique_constraint(op.f('representatives_code_key'), 'representatives', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('representatives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('representatives', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('representatives', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_visit_plans_id'), table_name='visit_plans')
    op.drop_index(op.f('ix_visit_plans_code'), table_name='visit_plans')
    op.drop_table('visit_plans')
    # ### end Alembic commands ###
